language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

services:
  - redis-server

matrix:
    allow_failures:

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry sudo redis-server /etc/redis/redis.conf --port 12701

script:
  - vendor/bin/phpunit --coverage-text

notifications:
  slack: huuinn:wXZ9PIZxjtHa5O9St4OxfzYj
